# Generated by Django 6.0.2 on 2026-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=30)),
                ('score', models.FloatField(default=0.0)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('tier', models.CharField(default='MAANG', max_length=50)),
                ('logo', models.CharField(default='google', max_length=50)),
                ('min_cutoff_score', models.FloatField(default=80.0)),
                ('hiring_status', models.CharField(default='Actively Hiring', max_length=50)),
                ('required_skills', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('aptitude', 'Aptitude Test'), ('technical', 'Technical Test')], default='aptitude', max_length=20)),
                ('section', models.CharField(choices=[('quantitative', 'Quantitative'), ('logical', 'Logical Reasoning'), ('verbal', 'Verbal Ability'), ('di', 'Data Interpretation'), ('python', 'Python'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('react', 'React'), ('django', 'Django')], default='quantitative', max_length=30)),
                ('difficulty', models.CharField(default='medium', max_length=15)),
                ('question_text', models.TextField()),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('options', models.JSONField()),
                ('correct_option_index', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
