# Generated by Django 6.0.2 on 2026-07-25 14:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='candidate', max_length=20)),
                ('headline', models.CharField(blank=True, default='Aspiring AI & Software Engineer', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_years', models.FloatField(default=2.0)),
                ('target_role', models.CharField(default='Full Stack Developer', max_length=100)),
                ('github_url', models.URLField(blank=True, default='https://github.com/developer', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/developer', null=True)),
                ('portfolio_url', models.URLField(blank=True, default='https://myportfolio.dev', null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('employability_score', models.FloatField(default=78.5)),
                ('resume_score', models.FloatField(default=82.0)),
                ('ats_score', models.FloatField(default=85.0)),
                ('aptitude_score', models.FloatField(default=75.0)),
                ('communication_score', models.FloatField(default=80.0)),
                ('technical_score', models.FloatField(default=78.0)),
                ('github_score', models.FloatField(default=84.0)),
                ('portfolio_score', models.FloatField(default=76.0)),
                ('linkedin_score', models.FloatField(default=79.0)),
                ('interview_score', models.FloatField(default=77.0)),
                ('personality_score', models.FloatField(default=81.0)),
                ('predicted_salary_min', models.IntegerField(default=1200000)),
                ('predicted_salary_max', models.IntegerField(default=1800000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
